import type { Metadata } from "next"
import "./globals.css"
import { UIProviders } from "@/components/Providers"

export const metadata: Metadata = {
  title: "NextMatch - Hope you won't die alone",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <UIProviders>{children}</UIProviders>
      </body>
    </html>
  )
}
